production:
  domain: 
  - name: "bricksco@bricksites.com"
    ssh_options:
    - "-p 2222"
  deploy_to: "public_html/micahredding/blog/sites/all"
  repository: "git@github.com:micahredding/drupal-micah-blog.git"
  branch: "master"